### PR TITLE
Rails stack

### PR DESCRIPTION
**Pull request by spk**
Allow a rails new project to run directly on upsun, ref https://github.com/platformsh/platformify/issues/205

- [x] make it work on platformsh too

### CODE REVIEW

**Comment by spk** [comment]
Yes I know those options I documented them from Ori work, the goal is to have a simple working bootstrap with Rails not a perfect one

**Comment by spk** [comment]
Can we give it a go and improve things later?

**Review by akalipetis — APPROVED** [review]
LGTM

@spk feel free to check the proposed changes and merge (or let me know to merge myself)

**Review by spk — COMMENTED** [review]
LGTM thanks @akalipetis

**Pull request merged**
